# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:6.6.1-jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - target/output
    - .gradle

build:
  stage: build
  script: gradle --build-cache install

test:
  stage: test
  script: gradle check